//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForgotPassword
    {
        public int ID { get; set; }
        public int P_ID { get; set; }
        public string U_ID { get; set; }
        public Nullable<System.DateTime> RequestDateTime { get; set; }
    
        public virtual LoginDetail LoginDetail { get; set; }
    }
}
