//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanAppliedDetail
    {
        public int ID { get; set; }
        public Nullable<int> P_ID { get; set; }
        public string Per_ID { get; set; }
        public Nullable<decimal> Per_Amount { get; set; }
        public Nullable<decimal> Per_Rate { get; set; }
        public Nullable<int> Per_Tenure { get; set; }
        public Nullable<decimal> Per_Emi { get; set; }
        public Nullable<decimal> Per_Last_Emi { get; set; }
        public Nullable<decimal> Per_Interest { get; set; }
        public string Home_ID { get; set; }
        public Nullable<decimal> Home_Amount { get; set; }
        public Nullable<decimal> Home_Rate { get; set; }
        public Nullable<int> Home_Tenure { get; set; }
        public Nullable<decimal> Home_Emi { get; set; }
        public Nullable<decimal> Home_Last_Emi { get; set; }
        public Nullable<decimal> Home_Interest { get; set; }
        public string Edu_ID { get; set; }
        public Nullable<decimal> Edu_Amount { get; set; }
        public Nullable<decimal> Edu_Rate { get; set; }
        public Nullable<int> Edu_Tenure { get; set; }
        public Nullable<decimal> Edu_Emi { get; set; }
        public Nullable<decimal> Edu_Last_Emi { get; set; }
        public Nullable<decimal> Edu_Interest { get; set; }
        public string Gold_ID { get; set; }
        public Nullable<decimal> Gold_Amount { get; set; }
        public Nullable<decimal> Gold_Rate { get; set; }
        public Nullable<int> Gold_Tenure { get; set; }
        public Nullable<decimal> Gold_Emi { get; set; }
        public Nullable<decimal> Gold_Last_Emi { get; set; }
        public Nullable<decimal> Gold_Interest { get; set; }
    
        public virtual LoginDetail LoginDetail { get; set; }
    }
}
